version: '3.8'

services:
  angular-dev:
    build:
      context: .
      target: build
    
    ports:
      - "4200:4200"
      
    command: npm start -- --host 0.0.0.0

    volumes:
      - .:/app
      
      - /app/node_modules